### ISSUE TITLE
Support for approximations in start_date=*? Progress-tracking

### ISSUE THREAD

**Issue by natrius** [OpenHistoricalMap/ohm-date-filter#8]
This issue could act as a progress-tracking for the values that are supported by the plugin in filtering. 

Base:
https://wiki.openstreetmap.org/wiki/Key:start_date

- [x] `start_date=2010`; where the year is known, but no more
- [x] `start_date=0897`; for 897 CE, leading numbers needed
- [x] `start_date=1848-07`; where the year and month are known
- [x] `start_date=2010-03-31`; for where the full date is known, using the format yyyy-mm-dd
- [ ] `start_date=~1855`; some time around 1855
- [ ] `start_date=1860s`; during the 1860s (i.e 1860 → 1869 inclusive)
- [ ] `start_date=~1940s`; probably during the 1940s)
- [ ] `start_date=480 BC`; for something that happened in that year
- [ ] `start_date=before 1855`; during 1854 or before
- [ ] `start_date=before 1910-01-20`; before a specific date - possibly when a photo was taken
- [ ] `start_date=after 1823`; (after 1 January 1823 - possibly based on the year in which a map was produced)
- [ ] `start_date=C18`; during the 18th century
- [ ] `start_date=mid C14`; some time during the middle of the 14th century
- [ ] `start_date=late 1920s`;
- [ ] `start_date=~C13`; probably in the 13th century
- [ ] `start_date=1914..1918`; indicates some time during WW1
- [ ] `start_date=2008-08-08..2008-08-24`; indicates some time during the Beijing Olympics
- [ ] `start_date=mid C17..late C17`; 

A checked box [x] indicated that the value is supported, a line thats ~~crossed out~~ indicates that this feature is not planned.

If its a bad idea, please just close the issue :) 

I tried right now with `start_date=late C13` and `start_date=~1855` and they did not work. I think for some there might be a discussion needed, as what to do when using `C18` for example.

**Comment by Rub21** [comment]
This is good, The above list make sense , that could be implemented too!! 

@jeffreyameyer , would be  good your inputs  here  as well ?

**Comment by natrius** [comment]
I started a thread for discussion, i thought this might get more input :) https://forum.openhistoricalmap.org/t/clarify-the-use-of-start-date-edtf/345
